from documenteer.conf.guide import *

exclude_patterns.append("requirements.txt")

# Warning generated by sphinx sitemaps not finding the git commit for the
# symlinked schema json.
suppress_warnings = ["git.dependency_not_found"]
